# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f2592aaed253f37330da7695a73319b37704c343fe2f58d6f531fd165f759f50ccccbabb6e8d299690d8b4a5d4ad8901965a46df983079909b25eb9d914b03d

test:
  secret_key_base: 58be2e856a996e1bf5784062ca338ecb4ba9d328f809efe405e17dac5d8b2b5d2e9ab8e20d24ed964da510e3beafd485df787f395d71e4ef71528833cc7d1329

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
